---
apiVersion: v1
kind: Service
metadata:
  name: ui
  labels:
    run: ui
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
  selector:
    run: ui
