---
apiVersion: v1
kind: Service
metadata:
  name: auth
  labels:
    run: auth
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9999
  type: ClusterIP
  selector:
    run: auth
