---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pi
spec:
  selector:
    matchLabels:
      run: pi
  replicas: 1
  template:
    metadata:
      labels:
        run: pi
    spec:
      containers:
        - name: pi
          image: ashraf1abdelrasool/pi:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8082
          env:
            - name: "SPRING_PROFILES_INCLUDE"
              value: "cloud"
