---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
spec:
  selector:
    matchLabels:
      run: ui
  replicas: 1
  template:
    metadata:
      labels:
        run: ui
    spec:
      containers:
        - name: ui
          image: ashraf1abdelrasool/ui:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ui
  labels:
    run: ui
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
  type: NodePort
  selector:
    run: ui